### ISSUE TITLE
PToolbar.xml = PToolBar.xml

### ISSUE THREAD

**Issue by marcovanderbijl** [chiefenne/PyAero#1]
FileNotFoundError: [Errno 2] No such file or directory: '/home/marco/Programs/PyAero-master/data/Menus/PToolbar.xml'
Segmentation fault (core dumped)

the file /home/marco/Programs/PyAero-master/data/Menus/PToolBar.xml does exist.

I simply copied the file and changed the name of the copy to be able to run the program.

**Comment by chiefenne** [comment]
Which version did you use? Did you run from source? In the actual source this should be correct.
The Windows executable unfortunately is outdated.

**Comment by chiefenne** [comment]
Sorry. You are right. This error does not show up when running the source under Windows (as it is not case sensitive).
Seems that I need to do some Linux testing.

**Comment by chiefenne** [comment]
fixed
