### ISSUE TITLE
Export of generated mesh

### ISSUE THREAD

**Issue by LucasPa** [chiefenne/PyAero#35]
Hello,

I am a new user of PyAero (version 2.1.5) and so far everything went fine in generating a mesh ... except as far as the export is concerned.

My first problem concerns the export of the boundaries:

- When exporting in GMSH format, I read the exported file with meshio (https://github.com/nschloe/meshio) and I can see that no edges have been written in the mesh file.
- When export in VTK format, I  read the exported file with meshio and Antares (from CERFACS) and I can see that no edges have been written in the mesh file.

Best,

Lucas

EDIT:

I don't have such a problem when using the SU2 export (that can be read as well with meshio). However I see that the boundary names are not written to the SU2 file.

**Comment by chiefenne** [comment]
Version 2.1.7 fixed the issue for the boundary edges for GMSH and SU2 formats. These exports have been refactored and do not rely on the meshio library anymore.
