### ISSUE TITLE
No QT platform plugin issue 

### ISSUE THREAD

**Issue by Logan-Price** [chiefenne/PyAero#4]
When I try and run the PyAero.py file I get this issue, and I don't know how to get around it.

I would really love to use the program but cannot at the moment. Thanks.

![Capture](https://user-images.githubusercontent.com/80018095/118068398-8afc7d00-b35f-11eb-8ef1-c9a9dc840a2a.JPG)

**Comment by chiefenne** [comment]
Hi,

sorry, but currently there is no support for the Windows version. I also do not work on the software at the moment (this is a hobby project).

I apologize for no better news.

Best regards,

Andreas
