### ISSUE TITLE
Exporting mesh .su2

### ISSUE THREAD

**Issue by m-nadal** [chiefenne/PyAero#5]
Dear @chiefenne,

I have been working to mesh a NACA0012 airfoil on PyAero thanks to your tutorial. When exporting the mesh to a .su2 file, then inputting it into SU2 and trying to run  a simulation, SU2 generates the error "Mismatch between NPOIN and number of points listed in mesh file. Please check the mesh file for correctness." I am guessing that's because additional supporting points are saved in the su2 file ? How can I get rid of the unused points in the list ?

Thanks for your help

**Comment by chiefenne** [comment]
I did some updates and released version 2.0
Hopefully this fixes your problems. The boundary definitiones does not work at the moment, you need to do this elsewhere.
